version: '3'
services:
  loader:
    build: './'
    environment:
     - TOKEN=${TOKEN}
     - APP_IDS=${API_KEYS}
     - SOURCE_NAME=${SOURCE_NAME:-events}
     - FIELDS=${FIELDS:-["event_name","event_timestamp","appmetrica_device_id","os_name","country_iso_code","city"]}
     - CH_HOST=http://db:8123
    depends_on:
     - db
  db:
    image: 'yandex/clickhouse-server'
    volumes:
      - db-data:/var/lib/clickhouse
volumes:
  db-data:
