version: '3'
services:
  loader:
    image: 'yandex/appmetrica-logsapi-loader'
    build: './'
    environment:
     - TOKEN=${TOKEN}
     - APP_IDS=${APP_IDS}
     - CH_HOST=http://db:8123
    depends_on:
     - db
  db:
    image: 'yandex/clickhouse-server'
    volumes:
      - db-data:/var/lib/clickhouse
volumes:
  db-data:
